export default {
  common: {
    confirm: 'Confirm',
    cancel: 'Cancel',
    back: 'Back',
    loading: 'Loading...',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search',
    notFound: 'Not Found',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    allCategories: 'All Categories'
  },
  nav: {
    home: 'Home',
    aiChat: 'AI Chat',
    my: 'My'
  },
  home: {
    title: 'News',
    more: 'More',
    refresh: 'Refresh',
    loadMore: 'Load More',
    noMore: 'No More',
    modeClassic: 'Feed',
    modeAI: 'AI Pick',
    aiLoginPrompt: 'Log in to get personalized recommendations',
    recommendFailed: 'Recommendation service unavailable, switched back to Feed',
    aiStrategyVector: 'Recommended based on your interests',
    aiStrategyHot: 'Trending · Read more to improve recommendations',
    categories: {
      headline: 'Headlines',
      society: 'Society',
      domestic: 'Domestic',
      international: 'International',
      entertainment: 'Entertainment',
      sports: 'Sports',
      military: 'Military',
      technology: 'Technology',
      finance: 'Finance',
      more: 'More'
    }
  },
  aiChat: {
    title: 'AI Chat',
    placeholder: 'Enter your question...',
    send: 'Send',
    thinking: 'AI is thinking...',
    history: 'History',
    loginTip: 'Log in to ask questions and keep chat history',
    welcome: 'Hi! I am an AI assistant that answers questions based on in-site news.',
    needLogin: 'Session expired, please log in again',
    serviceUnavailable: 'AI service is unavailable, please try again later',
    cancelled: 'Request cancelled',
    error: 'Request failed',
    sources: 'References'
  },
  aiHistory: {
    title: 'Chat History',
    loginPrompt: 'Log in to view chat history',
    empty: 'No chat records yet, go ask the AI assistant'
  },
  my: {
    title: 'My',
    notLoggedIn: 'Not Logged In',
    goToLogin: 'Login',
    goToRegister: 'Register',
    myFavorite: 'My Favorites',
    browsingHistory: 'Browsing History',
    notifications: 'Notifications',
    settings: 'Settings',
    logout: 'Logout',
    profile: 'Profile',
    myInterest: 'My Interests'
  },
  settings: {
    title: 'Settings',
    personalization: 'Personalization',
    themeCustomization: 'Theme Customization',
    languageSettings: 'Language Settings',
    account: 'Account',
    privacySettings: 'Privacy Settings',
    notificationSettings: 'Notification Settings',
    aboutUs: 'About Us',
    selectTheme: 'Select Theme',
    themeChanged: 'Theme changed',
    languageChanged: 'Language changed, some changes will take effect after restarting the app',
    selectLanguage: 'Select Language'
  },
  profile: {
    title: 'Profile',
    username: 'Username',
    bio: 'Bio',
    save: 'Save Changes',
    interestTags: 'My Interests',
    interestDesc: 'Generated by AI from your browsing and favorites. Read more to improve your recommendations.'
  },
  newsDetail: {
    aiSummary: 'AI Summary',
    aiTags: 'AI Tags',
    keywords: 'Keywords'
  }
};